using System.Net;
using Nabat.Core;
using Xunit;
namespace Nabat.Tests;
public sealed class OperationsTests
{
    [Fact] public void PixelOverlayIsTransparentForIdenticalImagesAndUsesPremultipliedColour(){Assert.Equal(new byte[]{0,0,0,0},PixelCompare.Heatmap([20,40,60,255],[20,40,60,255]));var changed=PixelCompare.Heatmap([0,0,0,255],[255,255,255,255]);Assert.True(changed[3]>0);Assert.All(changed.Take(3),channel=>Assert.True(channel<=changed[3]));}
    [Fact]public void ImageRegionsFitTheActualLetterboxedImage(){var fit=PixelCompare.Fit(100,100,1000,400);Assert.Equal(300,fit.X);Assert.Equal(0,fit.Y);Assert.Equal(400,fit.Width);}
    [Fact]public void TimelineUsesElapsedTimeRatherThanEvenlySpacedRecords(){var first=DateTimeOffset.Parse("2026-01-01T00:00:00Z");Assert.Equal(10,TimelineMath.X(first.AddDays(1),first,first.AddDays(100),1000));}
    [Fact] public void ComparisonUsesTheActualVersionedSignalNames(){const string signal="{\"visible_leaf_loss_estimate\":{\"value\":0.2,\"confidence\":0.7,\"evidence\":\"Saved visual estimate\"},\"canopy_size_estimate\":{\"value\":0.3,\"confidence\":0.6,\"evidence\":\"Saved canopy proxy\"},\"new_growth_signal\":{\"value\":0.1,\"confidence\":0.5,\"evidence\":\"Saved growth\"},\"wilting_signal\":{\"value\":0.4,\"confidence\":0.8,\"evidence\":\"Saved wilting\"}}";using var data=System.Text.Json.JsonDocument.Parse(signal);var result=ObservationCompare.Calculate(data.RootElement,data.RootElement);Assert.Equal(4,result.Count);Assert.All(result,r=>Assert.Equal(0,r.PercentagePoints));}
    [Fact] public void LegacyPostgresNumericsMapToNativeModels(){using var data=System.Text.Json.JsonDocument.Parse("{\"id\":\"plant\",\"name\":\"Ficus\",\"confidence\":\"0.7\",\"operations_revision\":\"12\",\"score\":82}");var plant=Contracts.Read<PlantSummary>(data.RootElement);Assert.Equal(.7,plant.Confidence);Assert.Equal(12,plant.OperationsRevision);}
    private static ApiSession Session(string actor="user-a")=>new("test-session",DateTimeOffset.UtcNow.AddDays(1),new(actor,"Tester","test@nabat.test"),[new("org","Hotel","owner","Asia/Dubai")]);
    private static string Db()=>Path.Combine(Path.GetTempPath(),"nabat-tests",Guid.NewGuid()+".db");
    private sealed class Handler(Func<HttpRequestMessage,Task<HttpResponseMessage>> action):HttpMessageHandler { protected override Task<HttpResponseMessage> SendAsync(HttpRequestMessage request,CancellationToken ct)=>action(request); }
    [Fact] public async Task OutboxSurvivesAStoreRestartAndDeduplicatesRequests(){var filename=Db();var store=new LocalStore(filename);await store.InitializeAsync();await store.EnqueueAsync("scope","org","org/care","{}","id");await store.EnqueueAsync("scope","org","org/care","{}","id");var reopened=new LocalStore(filename);await reopened.InitializeAsync();Assert.Single(await reopened.OutboxAsync("scope"));Assert.Empty(await reopened.OutboxAsync("other-user"));}
    [Fact] public async Task SuccessfulReplayRemovesOnlyAcknowledgedWork(){var calls=0;using var api=new ApiClient("http://127.0.0.1:3001",new Handler(r=>{Assert.Equal("test-session",r.Headers.Authorization!.Parameter);calls++;return Task.FromResult(new HttpResponseMessage(HttpStatusCode.OK){Content=new StringContent("{}")});})){Session=Session()};var store=new LocalStore(Db());await store.InitializeAsync();using var sync=new SyncEngine(api,store);await sync.QueueCareAsync("org",new("plant","watered",Guid.NewGuid().ToString(),DateTimeOffset.UtcNow.ToString("O")));await sync.SyncAsync("org");await sync.SyncAsync("org");Assert.Equal(1,calls);Assert.Empty(await store.OutboxAsync(api.Scope("org")));Assert.Equal("Synced",sync.Status);}
    [Fact] public async Task OfflineCareRemainsQueuedWithoutAnyNetworkRequest(){using var api=new ApiClient("https://nabat.example",new Handler(_=>throw new Exception("Must not access the network"))){Session=Session()};var store=new LocalStore(Db());await store.InitializeAsync();using var sync=new SyncEngine(api,store){WorkingOffline=true};await sync.QueueCareAsync("org",new("plant","inspected",Guid.NewGuid().ToString(),DateTimeOffset.UtcNow.ToString("O")));await sync.SyncAsync("org");Assert.Single(await store.OutboxAsync(api.Scope("org")));Assert.Equal("Working offline",sync.Status);}
    [Theory][InlineData(409)][InlineData(400)][InlineData(403)]public async Task RejectedMutationIsVisibleAndRetained(int status){using var api=new ApiClient("https://nabat.example",new Handler(_=>Task.FromResult(new HttpResponseMessage((HttpStatusCode)status){Content=new StringContent("{\"error\":\"Review this change\"}")}))){Session=Session()};var store=new LocalStore(Db());await store.InitializeAsync();using var sync=new SyncEngine(api,store);await sync.QueueCareAsync("org",new("plant","watered",Guid.NewGuid().ToString(),DateTimeOffset.UtcNow.ToString("O")));await sync.SyncAsync("org");var pending=Assert.Single(await store.OutboxAsync(api.Scope("org")));Assert.Equal("blocked",pending.State);Assert.Equal("Review this change",pending.Error);}
    [Fact]public async Task ExpiredAuthenticationPreservesWorkForSignIn(){using var api=new ApiClient("https://nabat.example",new Handler(_=>Task.FromResult(new HttpResponseMessage(HttpStatusCode.Unauthorized){Content=new StringContent("{}")}))){Session=Session()};var store=new LocalStore(Db());await store.InitializeAsync();using var sync=new SyncEngine(api,store);await sync.QueueCareAsync("org",new("plant","watered",Guid.NewGuid().ToString(),DateTimeOffset.UtcNow.ToString("O")));await sync.SyncAsync("org");Assert.Single(await store.OutboxAsync(api.Scope("org")));Assert.Contains("Sign in",sync.Status);}
    [Fact]public async Task NetworkFailureRetainsWorkWithBackoff(){using var api=new ApiClient("https://nabat.example",new Handler(_=>throw new HttpRequestException("offline"))){Session=Session()};var store=new LocalStore(Db());await store.InitializeAsync();using var sync=new SyncEngine(api,store);await sync.QueueCareAsync("org",new("plant","watered",Guid.NewGuid().ToString(),DateTimeOffset.UtcNow.ToString("O")));await sync.SyncAsync("org");var pending=Assert.Single(await store.OutboxAsync(api.Scope("org")));Assert.Equal(1,pending.Attempts);Assert.Empty(await store.OutboxAsync(api.Scope("org"),true));}
    [Fact]public void UserAndServerBoundariesHaveSeparateCacheScopes(){using var a=new ApiClient("https://a.nabat.example"){Session=Session()};using var b=new ApiClient("https://b.nabat.example"){Session=Session()};Assert.NotEqual(a.Scope("org"),b.Scope("org"));var original=a.Scope("org");a.Session=Session("user-b");Assert.NotEqual(original,a.Scope("org"));}
    [Theory][InlineData("http://example.com")][InlineData("https://user:secret@example.com")][InlineData("https://example.com/path")][InlineData("file:///C:/")]
    public void ServerConfigurationRejectsUnsafeEndpoints(string value)=>Assert.ThrowsAny<Exception>(()=>new ApiClient(value));
    [Theory][InlineData("https://nabat.example/p/abc")][InlineData("http://localhost:3001/p/xyz")]
    public async Task NdefEncodingVerifiesTheActualReadBack(string url){var writer=new SimulatedNfcAdapter();var data=NdefUri.Encode(url);await writer.WriteAsync(data);data[0]=0;Assert.Equal(url,NdefUri.Decode(await writer.ReadAsync()));}
    [Fact]public void MalformedNdefIsRejected()=>Assert.Throws<InvalidDataException>(()=>NdefUri.Decode([0xD1,1,20,0x55,4]));
    [Theory][InlineData("nabat://plant/NAB-001",true)][InlineData("nabat://plant/NAB-001?tenant=other",false)][InlineData("nabat://plant/../secret",false)][InlineData("https://plant/NAB-001",false)]
    public void DeepLinkAcceptsOnlyThePlantIdentityRoute(string url,bool valid)=>Assert.Equal(valid,PlantDeepLink.Parse(url) is not null);
}
