using CommunityToolkit.WinUI.UI.Controls;
using Microsoft.UI.Xaml;
using Microsoft.UI.Xaml.Controls;
using Microsoft.UI.Xaml.Data;
using Nabat.Core;
using System.Collections.ObjectModel;
using System.Text.Json;
namespace Nabat.Windows;

public sealed partial class MainWindow
{
    private string? _fleetLocation, _fleetAssignee, _fleetState; private bool _fleetOverdue, _fleetInspection; private int? _fleetNoObservation;
    private sealed class PlantGroup(string name, IEnumerable<PlantSummary> rows) : ObservableCollection<PlantSummary>(rows) { public string Name { get; } = name; }
    private async void ShowPlants()
    {
        var search = new AutoSuggestBox { PlaceholderText = "Search fleet", MinWidth = 220 }; var states = new ComboBox { ItemsSource = new[] { "All states", "healthy", "watch", "attention", "critical", "baseline" }, SelectedIndex = 0, MinWidth = 130 };
        if (_fleetState is not null) states.SelectedItem = _fleetState; var grouping = new ComboBox { ItemsSource = new[] { "none", "location", "state", "species", "assignee" }, SelectedIndex = 0, MinWidth = 120 }; var status = NativeUi.Caption(""); var saved = new ComboBox { PlaceholderText = "Saved views", MinWidth = 160, DisplayMemberPath = "Name" };
        var grid = new DataGrid { AutoGenerateColumns = false, IsReadOnly = true, SelectionMode = DataGridSelectionMode.Extended, CanUserReorderColumns = true, CanUserResizeColumns = true, CanUserSortColumns = true, FrozenColumnCount = 2, RowHeight = 58, Background = NativeUi.Brush("#FFFFFF"), GridLinesVisibility = DataGridGridLinesVisibility.Horizontal };
        var imageTemplate = (DataTemplate)Microsoft.UI.Xaml.Markup.XamlReader.Load("""<DataTemplate xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"><Image Source="{Binding Image}" Width="38" Height="44" Stretch="UniformToFill" AutomationProperties.Name="{Binding Name}"/></DataTemplate>"""); grid.Columns.Add(new DataGridTemplateColumn { Header = "Photo", CellTemplate = imageTemplate, Width = new DataGridLength(72), CanUserSort = false });
        foreach (var column in new[] { ("Plant", "Name", 190d), ("Code", "Code", 120d), ("Species", "SpeciesName", 155d), ("Location", "LocationText", 140d), ("Health", "ScoreText", 80d), ("State", "HealthState", 105d), ("Trend", "TrendText", 80d), ("Last care", "LastCareText", 150d), ("Next care", "NextCareText", 150d), ("Caretaker", "CaretakerText", 160d), ("Alerts", "ActiveAlerts", 70d), ("Observation", "ObservationText", 120d) }) { var style = new Style(typeof(TextBlock)); style.Setters.Add(new Setter(TextBlock.MarginProperty, new Thickness(10, 0, 10, 0))); style.Setters.Add(new Setter(TextBlock.TextTrimmingProperty, TextTrimming.CharacterEllipsis)); grid.Columns.Add(new DataGridTextColumn { Header = column.Item1, Binding = new Binding { Path = new(column.Item2) }, Width = new DataGridLength(column.Item3), ElementStyle = style }); }
        List<PlantSummary> current = []; int page = 0, total = 0; string sort = "priority", direction = "desc"; List<SavedView> views = []; var restoring = true; var initialQuery = await _store.PreferenceAsync("fleet-query:" + _api!.Scope(_org));
        void Group() { var name = grouping.SelectedItem?.ToString() ?? "none"; if (name == "none") { grid.ItemsSource = current; return; } var groups = current.GroupBy(p => name switch { "location" => p.LocationText, "species" => p.SpeciesName, "assignee" => p.CaretakerText, _ => p.HealthState }).Select(g => new PlantGroup(g.Key, g)).ToList(); var source = new CollectionViewSource { Source = groups, IsSourceGrouped = true }; grid.ItemsSource = source.View; }
        grid.LoadingRowGroup += (_, e) => { if (e.RowGroupHeader.CollectionViewGroup?.Group is PlantGroup group) e.RowGroupHeader.PropertyValue = group.Name; };
        async Task Load()
        {
            if (restoring) return;
            try
            {
                var route = $"{_org}/fleet?limit=100&page={page}&sort={sort}&direction={direction}&search={Uri.EscapeDataString(search.Text ?? "")}"; if (states.SelectedIndex > 0) route += "&state=" + states.SelectedItem; if (_fleetLocation is not null) route += "&location=" + _fleetLocation; if (_fleetAssignee is not null) route += "&assignee=" + _fleetAssignee; if (_fleetOverdue) route += "&overdue=true"; if (_fleetInspection) route += "&inspection=true"; if (_fleetNoObservation is not null) route += "&noObservationDays=" + _fleetNoObservation;
                if (_sync!.WorkingOffline) { current = _snapshot!.Plants.Where(p => (search.Text is null || $"{p.Name} {p.Code}".Contains(search.Text, StringComparison.OrdinalIgnoreCase)) && (states.SelectedIndex == 0 || p.HealthState == states.SelectedItem?.ToString())).ToList(); total = current.Count; } else { using var doc = JsonDocument.Parse(await _api!.GetAsync(route)); var result = Contracts.Read<FleetPage>(doc.RootElement); current = result.Items.Select(p => p with { Image = NativeUi.ImageUri(p.Image, _api.BaseUri)?.ToString() }).ToList(); total = result.Total; }
                Group(); status.Text = $"{(current.Count == 0 ? 0 : page * 100 + 1)}–{page * 100 + current.Count} / {total} plants · {grid.SelectedItems.Count} selected"; await _store.SetPreferenceAsync("fleet-query:" + _api!.Scope(_org), JsonSerializer.Serialize(new { search = search.Text, state = states.SelectedIndex, location = _fleetLocation, assignee = _fleetAssignee, overdue = _fleetOverdue, inspection = _fleetInspection, noObservationDays = _fleetNoObservation, sort, direction, groupBy = grouping.SelectedItem, columns = grid.Columns.Select(c => new { name = c.Header.ToString(), width = c.ActualWidth, visible = c.Visibility == Visibility.Visible, order = c.DisplayIndex }) }));
            }
            catch (Exception ex) { Message(ex.Message, true); }
        }
        async Task ViewList() { try { using var doc = JsonDocument.Parse(await _api!.GetAsync($"{_org}/views")); views = doc.RootElement.EnumerateArray().Select(v => new SavedView(v.GetProperty("id").GetString()!, v.GetProperty("name").GetString()!, v.GetProperty("filters").Clone())).ToList(); saved.ItemsSource = views; } catch (HttpRequestException) { } catch (ApiException) { } }
        var toolbar = new StackPanel { Orientation = Orientation.Horizontal, Spacing = 8 }; toolbar.Children.Add(search); toolbar.Children.Add(states); toolbar.Children.Add(saved); toolbar.Children.Add(grouping);
        toolbar.Children.Add(NativeUi.Button("Filters", async (_, _) => { var locations = new ComboBox { Header = "Location", ItemsSource = new[] { new Location("", "All locations", null) }.Concat(_snapshot!.Locations).ToList(), DisplayMemberPath = "Name", SelectedItem = _snapshot.Locations.FirstOrDefault(l => l.Id == _fleetLocation), MinWidth = 320 }; var caretaker = new ComboBox { Header = "Caretaker", ItemsSource = new[] { new Member("", "All caretakers", "") }.Concat(_snapshot.Team).ToList(), DisplayMemberPath = "Name", MinWidth = 320 }; var overdue = new CheckBox { Content = "Care overdue", IsChecked = _fleetOverdue }; var inspect = new CheckBox { Content = "Needs inspection", IsChecked = _fleetInspection }; var old = new CheckBox { Content = "No observation in 30 days", IsChecked = _fleetNoObservation is not null }; var dialog = new ContentDialog { XamlRoot = Root.XamlRoot, Title = "Advanced fleet filters", Content = NativeUi.Stack(locations, caretaker, overdue, inspect, old), PrimaryButtonText = "Apply filters", SecondaryButtonText = "Clear filters", CloseButtonText = "Cancel" }; var choice = await dialog.ShowAsync(); if (choice == ContentDialogResult.None) return; _fleetLocation = choice == ContentDialogResult.Secondary ? null : (locations.SelectedItem as Location)?.Id; _fleetAssignee = choice == ContentDialogResult.Secondary ? null : (caretaker.SelectedItem as Member)?.UserId; if (_fleetLocation == "") _fleetLocation = null; if (_fleetAssignee == "") _fleetAssignee = null; _fleetOverdue = choice == ContentDialogResult.Primary && overdue.IsChecked == true; _fleetInspection = choice == ContentDialogResult.Primary && inspect.IsChecked == true; _fleetNoObservation = choice == ContentDialogResult.Primary && old.IsChecked == true ? 30 : null; page = 0; await Load(); }));
        var columns = new MenuFlyout(); foreach (var column in grid.Columns) { var toggle = new ToggleMenuFlyoutItem { Text = column.Header.ToString(), IsChecked = true }; toggle.Click += (_, _) => column.Visibility = toggle.IsChecked ? Visibility.Visible : Visibility.Collapsed; columns.Items.Add(toggle); }
        toolbar.Children.Add(new DropDownButton { Content = "Columns", Flyout = columns });
        var commands = new StackPanel { Orientation = Orientation.Horizontal, Spacing = 8 }; commands.Children.Add(NativeUi.Button("Previous", async (_, _) => { page = Math.Max(0, page - 1); await Load(); })); commands.Children.Add(NativeUi.Button("Next", async (_, _) => { if ((page + 1) * 100 < total) { page++; await Load(); } })); commands.Children.Add(NativeUi.Button("Save view", async (_, _) => { var name = new TextBox { Header = "View name", MinWidth = 300 }; var dialog = new ContentDialog { XamlRoot = Root.XamlRoot, Title = "Save operational view", Content = name, PrimaryButtonText = "Save view", CloseButtonText = "Cancel" }; if (await dialog.ShowAsync() != ContentDialogResult.Primary) return; try { await _api!.PostAsync($"{_org}/views", new { name = name.Text, filters = new { search = search.Text, state = states.SelectedIndex > 0 ? states.SelectedItem?.ToString() : null, location = _fleetLocation, assignee = _fleetAssignee, overdue = _fleetOverdue, inspection = _fleetInspection, noObservationDays = _fleetNoObservation, sort, direction }, columns = grid.Columns.Where(c => c.Visibility == Visibility.Visible).OrderBy(c => c.DisplayIndex).Select(c => c.Header.ToString()).ToArray(), groupBy = grouping.SelectedItem.ToString(), idempotencyKey = Guid.NewGuid().ToString() }); await ViewList(); Message("Named view saved."); } catch (Exception ex) { Message(ex.Message, true); } })); commands.Children.Add(NativeUi.Button("Export loaded CSV", async (_, _) => await ExportCsv(current)));
        foreach (var action in new[] { "assign", "move", "schedule", "inspect", "labels" }) { var name = action; var button = NativeUi.Button("Bulk " + name, async (_, _) => { if (name is "assign" or "move") await BulkDialog(grid, name); else await BulkWorkDialog(grid, name); await Load(); }); button.IsEnabled = CanManage; commands.Children.Add(button); }
        commands.Children.Add(NativeUi.Button("Import photos", (_, _) => OpenImport()));
        search.QuerySubmitted += async (_, _) => { page = 0; await Load(); }; states.SelectionChanged += async (_, _) => { page = 0; await Load(); }; grouping.SelectionChanged += (_, _) => Group();
        saved.SelectionChanged += async (_, _) => { if (saved.SelectedItem is not SavedView view) return; var filter = view.Filters; search.Text = filter.GetProperty("search").GetString(); states.SelectedItem = filter.TryGetProperty("state", out var state) ? state.GetString() : "All states"; if (states.SelectedIndex < 0) states.SelectedIndex = 0; _fleetLocation = filter.TryGetProperty("location", out var location) ? location.GetString() : null; _fleetAssignee = filter.TryGetProperty("assignee", out var assignee) ? assignee.GetString() : null; _fleetOverdue = filter.TryGetProperty("overdue", out var late) && late.GetBoolean(); _fleetInspection = filter.TryGetProperty("inspection", out var check) && check.GetBoolean(); _fleetNoObservation = filter.TryGetProperty("noObservationDays", out var days) ? days.GetInt32() : null; grouping.SelectedItem = filter.TryGetProperty("groupBy", out var group) ? group.GetString() : "none"; if (filter.TryGetProperty("columns", out var visible)) { var names = visible.EnumerateArray().Select(v => v.GetString()).ToArray(); foreach (var c in grid.Columns) c.Visibility = names.Contains(c.Header.ToString()) ? Visibility.Visible : Visibility.Collapsed; for (var i = 0; i < names.Length; i++) { var c = grid.Columns.FirstOrDefault(c => c.Header.ToString() == names[i]); if (c is not null) c.DisplayIndex = i; } } page = 0; await Load(); };
        grid.SelectionChanged += (_, _) => status.Text = $"{current.Count} loaded / {total} plants · {grid.SelectedItems.Count} selected"; grid.DoubleTapped += (_, _) => { if (grid.SelectedItem is PlantSummary p) OpenPlant(p); }; grid.Sorting += async (_, e) => { sort = e.Column.Header.ToString() switch { "Plant" => "name", "Code" => "code", "Species" => "species", "Location" => "location", "Health" => "score", "State" => "score", "Trend" => "delta", "Last care" => "last_care", "Next care" => "next_care", "Caretaker" => "assignee", "Alerts" => "alerts", _ => "priority" }; direction = direction == "asc" ? "desc" : "asc"; await Load(); };
        var menu = new MenuFlyout(); void Action(string label, Action<PlantSummary> action) { var item = new MenuFlyoutItem { Text = label }; item.Click += (_, _) => { if (grid.SelectedItem is PlantSummary p) action(p); }; menu.Items.Add(item); }
        Action("Open plant in new window", OpenPlant); Action("Copy plant ID", p => Copy(p.Id)); Action("Copy plant link", p => Copy("nabat://plant/" + p.Code)); Action("Print tag", p => { _tagPlant = p.Id; Navigate("Tags"); }); Action("Log care", OpenPlant); grid.ContextFlyout = menu; grid.RightTapped += (_, e) => { var node = e.OriginalSource as DependencyObject; while (node is not null) { if (node is FrameworkElement { DataContext: PlantSummary p }) { grid.SelectedItem = p; break; } node = Microsoft.UI.Xaml.Media.VisualTreeHelper.GetParent(node); } };
        var layout = new Grid { RowSpacing = 12 }; for (var i = 0; i < 4; i++) layout.RowDefinitions.Add(new() { Height = i == 2 ? new(1, GridUnitType.Star) : GridLength.Auto }); layout.Children.Add(new ScrollViewer { Content = toolbar, HorizontalScrollBarVisibility = ScrollBarVisibility.Auto, HorizontalScrollMode = ScrollMode.Enabled }); Grid.SetRow(status, 1); layout.Children.Add(status); Grid.SetRow(grid, 2); layout.Children.Add(grid); var bar = new ScrollViewer { Content = commands, HorizontalScrollBarVisibility = ScrollBarVisibility.Auto, HorizontalScrollMode = ScrollMode.Enabled }; Grid.SetRow(bar, 3); layout.Children.Add(bar); SetView(layout);
        if (initialQuery is not null) try
            {
                using var restored = JsonDocument.Parse(initialQuery); var filter = restored.RootElement;
                search.Text = filter.GetProperty("search").GetString(); if (_fleetState is null) states.SelectedIndex = filter.GetProperty("state").GetInt32();
                if (_fleetLocation is null && _fleetAssignee is null && _fleetState is null && !_fleetOverdue && !_fleetInspection)
                {
                    _fleetLocation = filter.GetProperty("location").GetString(); _fleetAssignee = filter.GetProperty("assignee").GetString();
                    _fleetOverdue = filter.GetProperty("overdue").GetBoolean(); _fleetInspection = filter.GetProperty("inspection").GetBoolean();
                    _fleetNoObservation = filter.GetProperty("noObservationDays").ValueKind == JsonValueKind.Null ? null : filter.GetProperty("noObservationDays").GetInt32();
                }
                sort = filter.GetProperty("sort").GetString()!; direction = filter.GetProperty("direction").GetString()!; grouping.SelectedItem = filter.GetProperty("groupBy").GetString();
                if (filter.TryGetProperty("columns", out var layoutColumns)) foreach (var column in layoutColumns.EnumerateArray())
                {
                    var target = grid.Columns.FirstOrDefault(c => c.Header.ToString() == column.GetProperty("name").GetString());
                    if (target is null) continue; target.Width = new DataGridLength(Math.Clamp(column.GetProperty("width").GetDouble(), 50, 600)); target.Visibility = column.GetProperty("visible").GetBoolean() ? Visibility.Visible : Visibility.Collapsed; target.DisplayIndex = column.GetProperty("order").GetInt32();
                }
            }
            catch (Exception ex) when (ex is JsonException or KeyNotFoundException or InvalidOperationException) { }
        var storedColumns = await _store.PreferenceAsync("fleet-columns:" + _api!.Scope(_org));
        if (storedColumns is not null) try { using var columnDoc = JsonDocument.Parse(storedColumns); foreach (var column in columnDoc.RootElement.EnumerateArray()) { var target = grid.Columns.FirstOrDefault(c => c.Header.ToString() == column.GetProperty("name").GetString()); if (target is null) continue; target.Width = new DataGridLength(Math.Clamp(column.GetProperty("width").GetDouble(), 50, 600)); target.DisplayIndex = column.GetProperty("order").GetInt32(); } } catch (JsonException) { }
        restoring = false; await Load(); await ViewList();
        async Task PersistLayout() { if (restoring) return; await _store.SetPreferenceAsync("fleet-columns:" + _api!.Scope(_org), JsonSerializer.Serialize(grid.Columns.Select(c => new { name = c.Header.ToString(), width = c.ActualWidth, visible = c.Visibility == Visibility.Visible, order = c.DisplayIndex }))); }
        grid.ColumnReordered += async (_, _) => await PersistLayout();
        grid.PointerReleased += async (_, _) => await PersistLayout();
    }
    private record SavedView(string Id, string Name, JsonElement Filters);
    private string? _tagPlant;
    private async Task BulkWorkDialog(DataGrid grid, string action) { var plants = grid.SelectedItems.OfType<PlantSummary>().ToList(); if (plants.Count is 0 or > 100) { Message("Select 1–100 plants."); return; } var date = new CalendarDatePicker { Header = "Inspection date", Date = DateTimeOffset.Now }; var labels = new TextBox { Header = "Labels, separated by commas", MinWidth = 320 }; var owner = new ComboBox { Header = "Assigned caretaker", ItemsSource = _snapshot!.Team.Where(m => m.Role != "viewer").ToList(), DisplayMemberPath = "Name", MinWidth = 320 }; var detail = NativeUi.Stack(NativeUi.Text(plants.Count + " plants selected", 20, true), NativeUi.Caption(string.Join(", ", plants.Select(p => p.Code)))); if (action == "schedule") { detail.Children.Add(date); detail.Children.Add(owner); } if (action == "labels") detail.Children.Add(labels); var dialog = new ContentDialog { XamlRoot = Root.XamlRoot, Title = "Review bulk " + action, Content = detail, PrimaryButtonText = "Apply " + action, CloseButtonText = "Cancel" }; if (await dialog.ShowAsync() != ContentDialogResult.Primary) return; try { await _api!.PostAsync($"{_org}/bulk-work", new { plants = plants.Select(p => new { id = p.Id, revision = p.OperationsRevision }), action, dueAt = action == "schedule" ? date.Date?.ToUniversalTime().ToString("O") : null, assigneeId = (owner.SelectedItem as Member)?.UserId, labels = action == "labels" ? labels.Text.Split(',', StringSplitOptions.TrimEntries | StringSplitOptions.RemoveEmptyEntries) : null, idempotencyKey = Guid.NewGuid().ToString() }); Message("Bulk " + action + " recorded."); } catch (Exception ex) { Message(ex.Message, true); } }
}
