using Microsoft.UI.Xaml;
using Microsoft.UI.Xaml.Controls;
using Microsoft.UI.Xaml.Printing;
using global::Windows.Graphics.Printing;
using Nabat.Core;
using System.Text.Json;
namespace Nabat.Windows;

public sealed class ReportWindow : Window
{
    public int Days => _days;
    private readonly ApiClient _api; private readonly string _org; private readonly int _days;
    private readonly Grid _root = new() { Padding = new(28), RowSpacing = 16, Background = NativeUi.Brush("#F7F6EF") };
    private readonly StackPanel _content = NativeUi.Stack(); private JsonElement _report; private PrintDocument? _document; private PrintManager? _manager; private readonly List<UIElement> _pages = [];
    public ReportWindow(ApiClient api, string org, int days) { _api = api; _org = org; _days = days; Title = "NABAT operations report"; AppWindow.Resize(new global::Windows.Graphics.SizeInt32(1100, 900)); for (var i = 0; i < 2; i++) _root.RowDefinitions.Add(new() { Height = i == 1 ? new(1, GridUnitType.Star) : GridLength.Auto }); var commands = new StackPanel { Orientation = Orientation.Horizontal, Spacing = 8 }; commands.Children.Add(NativeUi.Button("Print / save PDF", async (_, _) => await Print())); commands.Children.Add(NativeUi.Button("Export report JSON", async (_, _) => await Export())); _root.Children.Add(commands); var scroll = new ScrollViewer { Content = _content }; Grid.SetRow(scroll, 1); _root.Children.Add(scroll); Content = _root; NativeUi.PrepareWindow(this, _root); _root.Loaded += async (_, _) => await Load(); Closed += (_, _) => { if (_manager is not null) _manager.PrintTaskRequested -= Requested; }; }
    private async Task Load() { try { using var data = JsonDocument.Parse(await _api.GetAsync($"{_org}/reports?days={_days}")); _report = data.RootElement.Clone(); _content.Children.Clear(); foreach (var line in Lines()) _content.Children.Add(NativeUi.Text(line, line == Lines()[0] ? 30 : 15, line == Lines()[0])); } catch (Exception ex) { _content.Children.Add(NativeUi.Text(ex.Message)); } }
    private List<string> Lines() { if (_report.ValueKind != JsonValueKind.Object) return ["Report is loading."]; var data = _report.GetProperty("data"); var overview = data.GetProperty("overview"); var operations = data.GetProperty("operations"); var lines = new List<string> { _report.GetProperty("title").GetString()!, _report.GetProperty("organisation").GetString()!, "Generated " + NativeUi.Date(_report.GetProperty("generatedAt").GetDateTimeOffset()), "Reporting range: " + _days + " days", "Fleet health", "Plants: " + NativeUi.Metric(overview, "total"), "Average health: " + NativeUi.Metric(overview, "average_health"), "Critical plants: " + NativeUi.Metric(overview, "critical"), "Rapid declines: " + NativeUi.Metric(overview, "rapid_decline"), "Maintenance sessions: " + NativeUi.Metric(operations, "sessions"), "Plants visited: " + NativeUi.Metric(operations, "visited"), "Recorded maintenance minutes: " + NativeUi.Metric(operations, "minutes"), "Attention plants" }; foreach (var plant in _report.GetProperty("attention").EnumerateArray()) lines.Add($"{plant.GetProperty("code")} · {plant.GetProperty("name")} · {plant.GetProperty("location_name")} · Health {plant.GetProperty("score")}"); lines.Add("Metric definitions"); lines.AddRange(_report.GetProperty("definitions").EnumerateArray().Select(v => v.GetString()!)); return lines; }
    private async Task Export() { if (_report.ValueKind != JsonValueKind.Object) return; var picker = new global::Windows.Storage.Pickers.FileSavePicker(); WinRT.Interop.InitializeWithWindow.Initialize(picker, WinRT.Interop.WindowNative.GetWindowHandle(this)); picker.SuggestedFileName = "NABAT-operations-report"; picker.FileTypeChoices.Add("JSON", new[] { ".json" }); var file = await picker.PickSaveFileAsync(); if (file is not null) await global::Windows.Storage.FileIO.WriteTextAsync(file, JsonSerializer.Serialize(_report, new JsonSerializerOptions { WriteIndented = true })); }
    private async Task Print() { try { if (_report.ValueKind != JsonValueKind.Object) return; if (_manager is null) { _manager = PrintManagerInterop.GetForWindow(WinRT.Interop.WindowNative.GetWindowHandle(this)); _manager.PrintTaskRequested += Requested; _document = new(); _document.Paginate += Paginate; _document.GetPreviewPage += (_, e) => _document.SetPreviewPage(e.PageNumber, _pages[e.PageNumber - 1]); _document.AddPages += (_, _) => { foreach (var page in _pages) _document.AddPage(page); _document.AddPagesComplete(); }; } await PrintManagerInterop.ShowPrintUIForWindowAsync(WinRT.Interop.WindowNative.GetWindowHandle(this)); } catch (Exception ex) { var dialog = new ContentDialog { XamlRoot = _root.XamlRoot, Title = "Printing unavailable", Content = ex.Message, CloseButtonText = "Close" }; await dialog.ShowAsync(); } }
    private void Requested(PrintManager sender, PrintTaskRequestedEventArgs args) => args.Request.CreatePrintTask("NABAT operations report", source => source.SetSource(_document!.DocumentSource));
    private void Paginate(object sender, PaginateEventArgs args) { _pages.Clear(); var description = ((PrintTaskOptions)args.PrintTaskOptions).GetPageDescription(0); var capacity = Math.Max(8, (int)((description.ImageableRect.Height - 80) / 36)); var lines = Lines(); for (var offset = 0; offset < lines.Count; offset += capacity) { var content = new StackPanel { Spacing = 10, Margin = new(48) }; content.Children.Add(NativeUi.Text("NABAT · Operations", 24, true)); foreach (var line in lines.Skip(offset).Take(capacity)) content.Children.Add(NativeUi.Text(line, 14)); content.Children.Add(NativeUi.Caption("Page " + (_pages.Count + 1))); _pages.Add(new Grid { Width = description.PageSize.Width, Height = description.PageSize.Height, Background = NativeUi.Brush("#FFFFFF"), Children = { content } }); } _document!.SetPreviewPageCount(_pages.Count, PreviewPageCountType.Final); }
}
