using Microsoft.UI.Xaml;
using Microsoft.UI.Xaml.Controls;
using Microsoft.UI.Xaml.Media;
using Nabat.Core;
using System.Text.Json;
namespace Nabat.Windows;

public sealed partial class MainWindow
{
    private sealed record TagRow(string Id, string PlantId, string Name, string Code, string State, string Url) { public string Display => Code + " · " + Name + " · " + State; }
    private async void ShowTags()
    {
        SetView(NativeUi.Text("Loading tag inventory…"));
        try
        {
            using var data = JsonDocument.Parse(await _api!.GetAsync($"{_org}/tags")); var tags = data.RootElement.EnumerateArray().Select(t => new TagRow(t.GetProperty("id").GetString()!, t.GetProperty("plant_id").GetString()!, t.GetProperty("name").GetString()!, t.GetProperty("code").GetString()!, t.GetProperty("state").GetString()!, t.GetProperty("resolver_url").GetString()!)).ToList();
            var list = new ListView { ItemsSource = tags, DisplayMemberPath = "Display", SelectionMode = ListViewSelectionMode.Extended, SelectedItem = tags.FirstOrDefault(t => t.PlantId == _tagPlant) ?? tags.FirstOrDefault() }; var preview = new Image { Width = 230, Height = 340, Stretch = Stretch.Uniform }; var url = NativeUi.Caption(""); var state = NativeUi.Caption(""); var template = new ComboBox { Header = "Physical template", ItemsSource = new[] { "label", "pot", "nursery", "thermal", "a4" }, SelectedIndex = 0, MinWidth = 240 };
            string svg = ""; byte[] png = []; TagRow? shown = null; int generation = 0; var actions = new List<Button>();
            async Task Preview()
            {
                var version = ++generation; foreach (var button in actions) button.IsEnabled = false; shown = null; url.Text = "Loading selected identity…"; if (list.SelectedItem is not TagRow row) return; var type = template.SelectedItem.ToString()!;
                try { var ids = list.SelectedItems.OfType<TagRow>().Take(16).Select(t => t.Id).ToArray(); var route = type == "a4" ? $"{_org}/tags/sheet?ids={string.Join(",", ids)}" : $"{_org}/tags/{row.Id}/artwork?template={type}"; var localSvg = await _api.GetAsync(route); var bytes = await _api.GetBytesAsync(type == "a4" ? route + "&format=png" : $"{_org}/tags/{row.Id}/preview?template={type}"); var bitmap = await NativeUi.Bitmap(bytes); if (version != generation) return; svg = localSvg; png = bytes; preview.Source = bitmap; shown = row; url.Text = row.Url; state.Text = row.Code + " · " + row.State; foreach (var button in actions) button.IsEnabled = true; }
                catch (Exception ex) { if (version == generation) { url.Text = "Preview unavailable"; Message(ex.Message, true); } }
            }
            var exportSvg = NativeUi.Button("Export SVG", async (_, _) => { if (shown is null) return; await SaveTagFile(svg, null, ".svg"); }); actions.Add(exportSvg);
            var exportPng = NativeUi.Button("Export PNG", async (_, _) => { if (shown is null) return; await SaveTagFile(null, png, ".png"); }); actions.Add(exportPng);
            var print = NativeUi.Button("Print / PDF", async (_, _) => { if (shown is null) return; try { var image = preview.Source; _printing?.Dispose(); var type = template.SelectedItem.ToString(); var size = type switch { "pot" => (35d, 35d), "nursery" => (50d, 90d), "thermal" => (60d, 40d), "a4" => (210d, 297d), _ => (45d, 65d) }; _printing = new(this, () => image, size.Item1, size.Item2); await _printing.ShowAsync(); } catch (Exception ex) { Message(ex.Message, true); } }); actions.Add(print);
            var station = NativeUi.Button("NFC Station", async (_, _) => { if (shown is not null) await NfcStation(shown); }); actions.Add(station);
            async Task Lifecycle(string action) { if (shown is null || shown.State != "active") { Message("Choose an active tag."); return; } var row = shown; var dialog = new ContentDialog { XamlRoot = Root.XamlRoot, Title = (action == "replace" ? "Replace" : "Retire") + " " + row.Code, Content = NativeUi.Caption("The current resolver will be retired. Plant identity and history stay intact."), PrimaryButtonText = action == "replace" ? "Replace tag" : "Retire tag", CloseButtonText = "Cancel" }; if (await dialog.ShowAsync() != ContentDialogResult.Primary) return; try { await _api.PostAsync($"{_org}/tags/{row.Id}/lifecycle", new { action, idempotencyKey = Guid.NewGuid().ToString() }); _tagPlant = row.PlantId; ShowTags(); } catch (Exception ex) { Message(ex.Message, true); } }
            var toolbar = new StackPanel { Orientation = Orientation.Horizontal, Spacing = 8 }; toolbar.Children.Add(NativeUi.Button("Replace identity tag", async (_, _) => await Lifecycle("replace"))); toolbar.Children.Add(NativeUi.Button("Retire tag", async (_, _) => await Lifecycle("retire")));
            var side = NativeUi.Stack(NativeUi.Text("Tag Studio", 26, true), template, state, preview, url, NativeUi.Button("Copy resolver URL", (_, _) => { if (shown is not null) Copy(shown.Url); }), exportSvg, exportPng, print, station, NativeUi.Caption("A4: select up to 16 tags per sheet. Simulation and physical verification are recorded separately."));
            var panes = new Grid { ColumnSpacing = 20 }; panes.ColumnDefinitions.Add(new() { Width = new(1.3, GridUnitType.Star) }); panes.ColumnDefinitions.Add(new() { Width = new(1, GridUnitType.Star) }); panes.Children.Add(NativeUi.Panel(list)); var inspector = NativeUi.Panel(new ScrollViewer { Content = side }); Grid.SetColumn(inspector, 1); panes.Children.Add(inspector); var root = new Grid { RowSpacing = 12 }; root.RowDefinitions.Add(new() { Height = GridLength.Auto }); root.RowDefinitions.Add(new() { Height = new(1, GridUnitType.Star) }); root.Children.Add(toolbar); Grid.SetRow(panes, 1); root.Children.Add(panes); SetView(root); list.SelectionChanged += async (_, _) => await Preview(); template.SelectionChanged += async (_, _) => await Preview(); await Preview();
        }
        catch (Exception ex) { Message(ex.Message, true); }
    }
    private async Task SaveTagFile(string? text, byte[]? bytes, string extension) { var picker = new global::Windows.Storage.Pickers.FileSavePicker(); WinRT.Interop.InitializeWithWindow.Initialize(picker, WinRT.Interop.WindowNative.GetWindowHandle(this)); picker.SuggestedFileName = "NABAT-tags"; picker.FileTypeChoices.Add(extension.Trim('.').ToUpperInvariant(), new[] { extension }); var file = await picker.PickSaveFileAsync(); if (file is null) return; if (bytes is not null) await global::Windows.Storage.FileIO.WriteBytesAsync(file, bytes); else await global::Windows.Storage.FileIO.WriteTextAsync(file, text!); Message("Tag export saved."); }
    private async Task NfcStation(TagRow tag)
    {
        if (tag.State != "active") { Message("Retired identities cannot be programmed."); return; }
        var ndef = NdefUri.Encode(tag.Url); var status = NativeUi.Text("Checking PC/SC readers…"); List<string> readers = [];
        try { readers = await Task.Run(PcscNfcAdapter.Readers); status.Text = readers.Count == 0 ? "No reader connected · simulation is available." : readers.Count + " readers detected."; } catch (Exception ex) { status.Text = "PC/SC unavailable · " + ex.Message; }
        var reader = new ComboBox { Header = "Reader", ItemsSource = readers, SelectedIndex = readers.Count > 0 ? 0 : -1, MinWidth = 300 }; string uid = "";
        var read = NativeUi.Button("Read tag UID", async (_, _) => { if (reader.SelectedItem is not string selected) return; try { uid = await new PcscNfcAdapter(selected).UidAsync(); status.Text = "Tag detected · " + uid; } catch (Exception ex) { status.Text = ex.Message; } });
        var simulate = NativeUi.Button("Simulate encoding and verify", async (_, _) => { try { var adapter = new SimulatedNfcAdapter(); await adapter.WriteAsync(ndef); if (NdefUri.Decode(await adapter.ReadAsync()) != tag.Url) throw new InvalidDataException("Read-back mismatch."); await _api!.PostAsync($"{_org}/tags/{tag.Id}/programming", new { reader = "Simulated NFC adapter", uid = "53494D", verification = "simulated", url = tag.Url, idempotencyKey = Guid.NewGuid().ToString() }); status.Text = "Simulation verified and recorded. No physical tag was written."; } catch (Exception ex) { status.Text = ex.Message; } });
        var dialog = new ContentDialog { XamlRoot = Root.XamlRoot, Title = "NFC Station · " + tag.Code, Content = NativeUi.Stack(NativeUi.Caption(tag.Url), reader, status, read, simulate), PrimaryButtonText = "Write physical identity", IsPrimaryButtonEnabled = readers.Count > 0 && new Uri(tag.Url).Scheme == "https" && !new Uri(tag.Url).IsLoopback, CloseButtonText = "Close" };
        if (await dialog.ShowAsync() != ContentDialogResult.Primary || reader.SelectedItem is not string selectedReader) return;
        try { using var fresh = JsonDocument.Parse(await _api!.GetAsync($"{_org}/tags")); if (!fresh.RootElement.EnumerateArray().Any(t => t.GetProperty("id").GetString() == tag.Id && t.GetProperty("state").GetString() == "active" && t.GetProperty("resolver_url").GetString() == tag.Url)) throw new InvalidOperationException("Tag identity changed. Reload Tag Studio."); var adapter = new PcscNfcAdapter(selectedReader); uid = await adapter.UidAsync(); var review = new ContentDialog { XamlRoot = Root.XamlRoot, Title = "Review physical programming", Content = NativeUi.Stack(NativeUi.Text(tag.Code + " · UID " + uid), NativeUi.Caption(tag.Url), NativeUi.Caption("Existing NDEF data will be replaced and read back for verification.")), PrimaryButtonText = "Write and verify", CloseButtonText = "Cancel" }; if (await review.ShowAsync() != ContentDialogResult.Primary) return; await adapter.WriteAsync(ndef); await _api.PostAsync($"{_org}/tags/{tag.Id}/programming", new { reader = selectedReader, uid, verification = "client_read_back", url = tag.Url, idempotencyKey = Guid.NewGuid().ToString() }); Message("Physical read-back verified and recorded."); } catch (Exception ex) { Message("Programming did not finish: " + ex.Message, true); }
    }
}
